# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_learning_pb2 as federated__learning__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_learning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudCoreStub(object):
    """==================== SERVICE DEFINITIONS ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/federated_learning.CloudCore/RegisterDevice',
                request_serializer=federated__learning__pb2.DeviceInfo.SerializeToString,
                response_deserializer=federated__learning__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.ReadyForRound = channel.unary_unary(
                '/federated_learning.CloudCore/ReadyForRound',
                request_serializer=federated__learning__pb2.ReadyRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.ReadyResponse.FromString,
                _registered_method=True)
        self.GetAssignment = channel.unary_unary(
                '/federated_learning.CloudCore/GetAssignment',
                request_serializer=federated__learning__pb2.AssignmentRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.AssignmentResponse.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/federated_learning.CloudCore/GetGlobalModel',
                request_serializer=federated__learning__pb2.ModelRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.ReportMetrics = channel.unary_unary(
                '/federated_learning.CloudCore/ReportMetrics',
                request_serializer=federated__learning__pb2.EdgeMetricsReport.SerializeToString,
                response_deserializer=federated__learning__pb2.MetricsAck.FromString,
                _registered_method=True)
        self.GetModelForDevice = channel.unary_unary(
                '/federated_learning.CloudCore/GetModelForDevice',
                request_serializer=federated__learning__pb2.DeviceModelRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.ModelResponse.FromString,
                _registered_method=True)


class CloudCoreServicer(object):
    """==================== SERVICE DEFINITIONS ====================
    """

    def RegisterDevice(self, request, context):
        """Device registration and coordination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadyForRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetrics(self, request, context):
        """Edge metrics reporting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelForDevice(self, request, context):
        """Device can directly get global model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=federated__learning__pb2.DeviceInfo.FromString,
                    response_serializer=federated__learning__pb2.RegistrationResponse.SerializeToString,
            ),
            'ReadyForRound': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadyForRound,
                    request_deserializer=federated__learning__pb2.ReadyRequest.FromString,
                    response_serializer=federated__learning__pb2.ReadyResponse.SerializeToString,
            ),
            'GetAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssignment,
                    request_deserializer=federated__learning__pb2.AssignmentRequest.FromString,
                    response_serializer=federated__learning__pb2.AssignmentResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=federated__learning__pb2.ModelRequest.FromString,
                    response_serializer=federated__learning__pb2.ModelResponse.SerializeToString,
            ),
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=federated__learning__pb2.EdgeMetricsReport.FromString,
                    response_serializer=federated__learning__pb2.MetricsAck.SerializeToString,
            ),
            'GetModelForDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelForDevice,
                    request_deserializer=federated__learning__pb2.DeviceModelRequest.FromString,
                    response_serializer=federated__learning__pb2.ModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated_learning.CloudCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated_learning.CloudCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudCore(object):
    """==================== SERVICE DEFINITIONS ====================
    """

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.CloudCore/RegisterDevice',
            federated__learning__pb2.DeviceInfo.SerializeToString,
            federated__learning__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadyForRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.CloudCore/ReadyForRound',
            federated__learning__pb2.ReadyRequest.SerializeToString,
            federated__learning__pb2.ReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.CloudCore/GetAssignment',
            federated__learning__pb2.AssignmentRequest.SerializeToString,
            federated__learning__pb2.AssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.CloudCore/GetGlobalModel',
            federated__learning__pb2.ModelRequest.SerializeToString,
            federated__learning__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.CloudCore/ReportMetrics',
            federated__learning__pb2.EdgeMetricsReport.SerializeToString,
            federated__learning__pb2.MetricsAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelForDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.CloudCore/GetModelForDevice',
            federated__learning__pb2.DeviceModelRequest.SerializeToString,
            federated__learning__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EdgeNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetrics = channel.unary_unary(
                '/federated_learning.EdgeNode/GetMetrics',
                request_serializer=federated__learning__pb2.MetricsRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.ApplyStress = channel.unary_unary(
                '/federated_learning.EdgeNode/ApplyStress',
                request_serializer=federated__learning__pb2.StressRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.StressResponse.FromString,
                _registered_method=True)
        self.ReceiveData = channel.unary_unary(
                '/federated_learning.EdgeNode/ReceiveData',
                request_serializer=federated__learning__pb2.DataPayload.SerializeToString,
                response_deserializer=federated__learning__pb2.DataResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/federated_learning.EdgeNode/GetDeviceInfo',
                request_serializer=federated__learning__pb2.DeviceInfoRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.DeviceInfoResponse.FromString,
                _registered_method=True)
        self.StartTraining = channel.unary_unary(
                '/federated_learning.EdgeNode/StartTraining',
                request_serializer=federated__learning__pb2.TrainingRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.TrainingResponse.FromString,
                _registered_method=True)
        self.GetTrainingResults = channel.unary_unary(
                '/federated_learning.EdgeNode/GetTrainingResults',
                request_serializer=federated__learning__pb2.ResultsRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.ResultsResponse.FromString,
                _registered_method=True)
        self.GetTrainingLogs = channel.unary_unary(
                '/federated_learning.EdgeNode/GetTrainingLogs',
                request_serializer=federated__learning__pb2.LogsRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.LogsResponse.FromString,
                _registered_method=True)
        self.FetchGlobalModel = channel.unary_unary(
                '/federated_learning.EdgeNode/FetchGlobalModel',
                request_serializer=federated__learning__pb2.EdgeModelRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.ModelResponse.FromString,
                _registered_method=True)


class EdgeNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMetrics(self, request, context):
        """Metrics and status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyStress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveData(self, request, context):
        """Device data handling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Training management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchGlobalModel(self, request, context):
        """Model fetching from cloud
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=federated__learning__pb2.MetricsRequest.FromString,
                    response_serializer=federated__learning__pb2.MetricsResponse.SerializeToString,
            ),
            'ApplyStress': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyStress,
                    request_deserializer=federated__learning__pb2.StressRequest.FromString,
                    response_serializer=federated__learning__pb2.StressResponse.SerializeToString,
            ),
            'ReceiveData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveData,
                    request_deserializer=federated__learning__pb2.DataPayload.FromString,
                    response_serializer=federated__learning__pb2.DataResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=federated__learning__pb2.DeviceInfoRequest.FromString,
                    response_serializer=federated__learning__pb2.DeviceInfoResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=federated__learning__pb2.TrainingRequest.FromString,
                    response_serializer=federated__learning__pb2.TrainingResponse.SerializeToString,
            ),
            'GetTrainingResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingResults,
                    request_deserializer=federated__learning__pb2.ResultsRequest.FromString,
                    response_serializer=federated__learning__pb2.ResultsResponse.SerializeToString,
            ),
            'GetTrainingLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingLogs,
                    request_deserializer=federated__learning__pb2.LogsRequest.FromString,
                    response_serializer=federated__learning__pb2.LogsResponse.SerializeToString,
            ),
            'FetchGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchGlobalModel,
                    request_deserializer=federated__learning__pb2.EdgeModelRequest.FromString,
                    response_serializer=federated__learning__pb2.ModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated_learning.EdgeNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated_learning.EdgeNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/GetMetrics',
            federated__learning__pb2.MetricsRequest.SerializeToString,
            federated__learning__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyStress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/ApplyStress',
            federated__learning__pb2.StressRequest.SerializeToString,
            federated__learning__pb2.StressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/ReceiveData',
            federated__learning__pb2.DataPayload.SerializeToString,
            federated__learning__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/GetDeviceInfo',
            federated__learning__pb2.DeviceInfoRequest.SerializeToString,
            federated__learning__pb2.DeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/StartTraining',
            federated__learning__pb2.TrainingRequest.SerializeToString,
            federated__learning__pb2.TrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/GetTrainingResults',
            federated__learning__pb2.ResultsRequest.SerializeToString,
            federated__learning__pb2.ResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/GetTrainingLogs',
            federated__learning__pb2.LogsRequest.SerializeToString,
            federated__learning__pb2.LogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.EdgeNode/FetchGlobalModel',
            federated__learning__pb2.EdgeModelRequest.SerializeToString,
            federated__learning__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
